name: Build PyPI

jobs:
  linting:
    name: Reuse linting job
    uses: ./.github/workflows/linting.yml

  build:
    needs: linting
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    #environment: production
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 #full history
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install hatch
      - name: Build project
        run: hatch build
