name: Build and publish to PyPI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Reuse build
    uses: ./.github/workflows/build.yml

  publish-to-test-pypi:
    needs: build
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    # environment: production
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Publish distribution 📦 to PyPI
        # if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1.8
        with:
          sign-artifacts: true
