name: Build and publish to Test PyPI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Reuse build
    uses: ./.github/workflows/build.yml

  publish-to-test-pypi:
    needs: build
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    # environment: development
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.8
        with:
          repository-url: https://test.pypi.org/legacy/
          sign-artifacts: true
          skip-existing: true
