name: Build and publish to Test PyPI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pip package(s)
        run: pip install hatch
      - name: Run black formatter check
        run: hatch run lint:black --check --verbose src tests
      - name: Run flake8 linter
        run: hatch run lint:flake8
      - name: Run unit and integrations tests
        run: hatch run test:pytest --cov=openapi-to-asciidoc --cov-report=xml --cov-report=html

  build:
    needs: linting
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    #environment: production
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 #full history
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install hatch
      - name: Build project
        run: hatch build

  publish-to-test-pypi:
    needs: build
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment:
      name: development
      url: https://test.pypi.org/p/openapi-to-asciidoc
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          # sign-artifacts: true
          # skip-existing: true
