name: Build and publish to PyPI
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pip package(s)
        run: pip install hatch
      - name: Run black formatter check
        run: hatch run lint:black --check --verbose src tests
      - name: Run flake8 linter
        run: hatch run lint:flake8
      - name: Run unit and integrations tests
        run: hatch run test:pytest --cov=openapi-to-asciidoc --cov-report=xml --cov-report=html

  build-and-publish:
    needs: linting
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 #full history
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install hatch
      - name: Build package
        run: hatch build
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          sign-artifacts: true
          skip-existing: true
      # - name: Publish distribution 📦 to PyPI
      #   if: startsWith(github.ref, 'refs/tags')
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     sign-artifacts: true
